---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 10m0s
  # dependsOn:
  #   - name: core
  path: ./k8s/namespaces/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: core
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   path: ./k8s/core/overlays/production
#   prune: false
#   sourceRef:
#     kind: GitRepository
#     name: flux-system